version: '3.8'

services:
  discovery-service:
    build:
      dockerfile: ../Dockerfile
      context: ./discovery-service
      args:
        JAR_FILE_NAME: discovery-service-0.0.1-SNAPSHOT.jar
    image: kageja/springcloudgateway-zuulproxy-example/discovery-service
    healthcheck:
      test: "wget --spider -q http://localhost:8761/actuator/health || exit 1"
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 10
    networks:
      - zuulproxy-example-net
  apigateway:
    environment:
      - SPRING_EUREKA_SERVER=discovery-service
    build:
      dockerfile: ../Dockerfile
      context: ./springcloudgateway
      args:
        JAR_FILE_NAME: springcloudgateway-0.0.1-SNAPSHOT.jar
    image: kageja/springcloudgateway-zuulproxy-example/springcloudgateway
    healthcheck:
      test: "wget --spider -q http://localhost:8080/actuator/health || exit 1"
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 10
    depends_on:
      - discovery-service
    ports:
      - 8080:8080
    networks:
      - zuulproxy-example-net
  producer:
    environment:
      - SPRING_EUREKA_SERVER=discovery-service
    build:
      dockerfile: ../Dockerfile
      context: ./producer
      args:
        JAR_FILE_NAME: producer-0.0.1-SNAPSHOT.jar
    image: kageja/springcloudgateway-zuulproxy-example/producer
    healthcheck:
      test: "wget --spider -q http://localhost:8038/actuator/health || exit 1"
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 10
    depends_on:
      - discovery-service
      - apigateway
    networks:
      - zuulproxy-example-net
  consumer:
    environment:
      - SPRING_EUREKA_SERVER=discovery-service
    build:
      dockerfile: ../Dockerfile
      context: ./consumer
      args:
        JAR_FILE_NAME: consumer-0.0.1-SNAPSHOT.jar
    image: kageja/springcloudgateway-zuulproxy-example/consumer
    healthcheck:
      test: "wget --spider -q http://localhost:8039/actuator/health || exit 1"
      interval: 2s
      timeout: 5s
      start_period: 2s
      retries: 10
    depends_on:
      - discovery-service
      - apigateway
      - producer
    networks:
      - zuulproxy-example-net

networks:
  zuulproxy-example-net: